/* -LICENSE-START-
 ** Copyright (c) 2016 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */


// Register 'IDENTIFIER'
var kRegIDENTIFIER       = 0x0000;
var kRegIDENTIFIER_Width = 4;
var kRegIDENTIFIER_Start = 0x0000;
var kRegIDENTIFIER_End   = 0x0003;

// Register Field 'IDENTIFIER.IDENTITY'
var kRegIDENTIFIER_IDENTITY_Offset = 0;
var kRegIDENTIFIER_IDENTITY_Width  = 32;
var kRegIDENTIFIER_IDENTITY_Mask   = 0xffffffff;

// Register 'FWVERSION'
var kRegFWVERSION       = 0x0004;
var kRegFWVERSION_Width = 2;
var kRegFWVERSION_Start = 0x0004;
var kRegFWVERSION_End   = 0x0005;

// Register Field 'FWVERSION.MINOR'
var kRegFWVERSION_MINOR_Offset = 0;
var kRegFWVERSION_MINOR_Width  = 8;
var kRegFWVERSION_MINOR_Mask   = 0x00ff;

// Register Field 'FWVERSION.MAJOR'
var kRegFWVERSION_MAJOR_Offset = 8;
var kRegFWVERSION_MAJOR_Width  = 8;
var kRegFWVERSION_MAJOR_Mask   = 0xff00;

// Register 'PVERSION'
var kRegPVERSION       = 0x0006;
var kRegPVERSION_Width = 2;
var kRegPVERSION_Start = 0x0006;
var kRegPVERSION_End   = 0x0007;

// Register Field 'PVERSION.MINOR'
var kRegPVERSION_MINOR_Offset = 0;
var kRegPVERSION_MINOR_Width  = 8;
var kRegPVERSION_MINOR_Mask   = 0x00ff;

// Register Field 'PVERSION.MAJOR'
var kRegPVERSION_MAJOR_Offset = 8;
var kRegPVERSION_MAJOR_Width  = 8;
var kRegPVERSION_MAJOR_Mask   = 0xff00;

// Register 'CONTROL'
var kRegCONTROL       = 0x1000;
var kRegCONTROL_Width = 1;
var kRegCONTROL_Start = 0x1000;
var kRegCONTROL_End   = 0x1000;

// Register Field 'CONTROL.COVERIDE'
var kRegCONTROL_COVERIDE_Offset = 0;
var kRegCONTROL_COVERIDE_Width  = 1;
var kRegCONTROL_COVERIDE_Mask   = 0x01;

// Register Field 'CONTROL.TOVERIDE'
var kRegCONTROL_TOVERIDE_Offset = 1;
var kRegCONTROL_TOVERIDE_Width  = 1;
var kRegCONTROL_TOVERIDE_Mask   = 0x02;

// Register Field 'CONTROL.TRESET'
var kRegCONTROL_TRESET_Offset = 2;
var kRegCONTROL_TRESET_Width  = 1;
var kRegCONTROL_TRESET_Mask   = 0x04;

// Register Field 'CONTROL.OOVERIDE'
var kRegCONTROL_OOVERIDE_Offset = 3;
var kRegCONTROL_OOVERIDE_Width  = 1;
var kRegCONTROL_OOVERIDE_Mask   = 0x08;

// Register 'OCARM'
var kRegOCARM       = 0x2000;
var kRegOCARM_Width = 1;
var kRegOCARM_Start = 0x2000;
var kRegOCARM_End   = 0x2000;

// Register Field 'OCARM.ARM'
var kRegOCARM_ARM_Offset = 0;
var kRegOCARM_ARM_Width  = 1;
var kRegOCARM_ARM_Mask   = 0x01;

// Register 'OCLENGTH'
var kRegOCLENGTH       = 0x2001;
var kRegOCLENGTH_Width = 1;
var kRegOCLENGTH_Start = 0x2001;
var kRegOCLENGTH_End   = 0x2001;

// Register Field 'OCLENGTH.LENGTH'
var kRegOCLENGTH_LENGTH_Offset = 0;
var kRegOCLENGTH_LENGTH_Width  = 8;
var kRegOCLENGTH_LENGTH_Mask   = 0xff;

// Register 'OCDATA'
var kRegOCDATA       = 0x2100;
var kRegOCDATA_Width = 255;
var kRegOCDATA_Start = 0x2100;
var kRegOCDATA_End   = 0x21fe;

// Register 'ICARM'
var kRegICARM       = 0x3000;
var kRegICARM_Width = 1;
var kRegICARM_Start = 0x3000;
var kRegICARM_End   = 0x3000;

// Register Field 'ICARM.ARM'
var kRegICARM_ARM_Offset = 0;
var kRegICARM_ARM_Width  = 1;
var kRegICARM_ARM_Mask   = 0x01;

// Register 'ICLENGTH'
var kRegICLENGTH       = 0x3001;
var kRegICLENGTH_Width = 1;
var kRegICLENGTH_Start = 0x3001;
var kRegICLENGTH_End   = 0x3001;

// Register Field 'ICLENGTH.LENGTH'
var kRegICLENGTH_LENGTH_Offset = 0;
var kRegICLENGTH_LENGTH_Width  = 8;
var kRegICLENGTH_LENGTH_Mask   = 0xff;

// Register 'ICDATA'
var kRegICDATA       = 0x3100;
var kRegICDATA_Width = 255;
var kRegICDATA_Start = 0x3100;
var kRegICDATA_End   = 0x31fe;

// Register 'OTARM'
var kRegOTARM       = 0x4000;
var kRegOTARM_Width = 1;
var kRegOTARM_Start = 0x4000;
var kRegOTARM_End   = 0x4000;

// Register Field 'OTARM.ARM'
var kRegOTARM_ARM_Offset = 0;
var kRegOTARM_ARM_Width  = 1;
var kRegOTARM_ARM_Mask   = 0x01;

// Register 'OTLENGTH'
var kRegOTLENGTH       = 0x4001;
var kRegOTLENGTH_Width = 1;
var kRegOTLENGTH_Start = 0x4001;
var kRegOTLENGTH_End   = 0x4001;

// Register Field 'OTLENGTH.LENGTH'
var kRegOTLENGTH_LENGTH_Offset = 0;
var kRegOTLENGTH_LENGTH_Width  = 8;
var kRegOTLENGTH_LENGTH_Mask   = 0xff;

// Register 'OTDATA'
var kRegOTDATA       = 0x4100;
var kRegOTDATA_Width = 255;
var kRegOTDATA_Start = 0x4100;
var kRegOTDATA_End   = 0x41fe;

// Register Field 'OTDATA.PROGRAM'
var kRegOTDATA_PROGRAM_Offset = 0;
var kRegOTDATA_PROGRAM_Width  = 1;
var kRegOTDATA_PROGRAM_Mask   = 0x01;

// Register Field 'OTDATA.PREVIEW'
var kRegOTDATA_PREVIEW_Offset = 1;
var kRegOTDATA_PREVIEW_Width  = 1;
var kRegOTDATA_PREVIEW_Mask   = 0x02;

// Register 'ITARM'
var kRegITARM       = 0x5000;
var kRegITARM_Width = 1;
var kRegITARM_Start = 0x5000;
var kRegITARM_End   = 0x5000;

// Register Field 'ITARM.ARM'
var kRegITARM_ARM_Offset = 0;
var kRegITARM_ARM_Width  = 1;
var kRegITARM_ARM_Mask   = 0x01;

// Register 'ITLENGTH'
var kRegITLENGTH       = 0x5001;
var kRegITLENGTH_Width = 1;
var kRegITLENGTH_Start = 0x5001;
var kRegITLENGTH_End   = 0x5001;

// Register Field 'ITLENGTH.LENGTH'
var kRegITLENGTH_LENGTH_Offset = 0;
var kRegITLENGTH_LENGTH_Width  = 8;
var kRegITLENGTH_LENGTH_Mask   = 0xff;

// Register 'ITDATA'
var kRegITDATA       = 0x5100;
var kRegITDATA_Width = 255;
var kRegITDATA_Start = 0x5100;
var kRegITDATA_End   = 0x51fe;

// Register Field 'ITDATA.PROGRAM'
var kRegITDATA_PROGRAM_Offset = 0;
var kRegITDATA_PROGRAM_Width  = 1;
var kRegITDATA_PROGRAM_Mask   = 0x01;

// Register Field 'ITDATA.PREVIEW'
var kRegITDATA_PREVIEW_Offset = 1;
var kRegITDATA_PREVIEW_Width  = 1;
var kRegITDATA_PREVIEW_Mask   = 0x02;
